name: Run Python Script

on:
  schedule:
    - cron: '*/1 * * * *'  # Wykonuj co 10 minut
  workflow_dispatch:  # Umożliwia ręczne uruchomienie

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Ustaw wersję Pythona, np. 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Check Python version
        run: python --version

      - name: Run script
        run: python scripts/solar_flare_bot.py  # Zmodyfikuj ścieżkę, jeśli to konieczne
